INSERT INTO factory (ID,NAME,COUNTRYCODE) VALUES (1,"TOYOTA",55);
INSERT INTO factory (ID,NAME,COUNTRYCODE) VALUES (2,"FORD",55);
INSERT INTO factory (ID,NAME,COUNTRYCODE) VALUES (3,"VOLKSWAGEN",55);
INSERT INTO factory (ID,NAME,COUNTRYCODE) VALUES (3,"FIAT",55);